version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /usr/local/share/save-point-docker/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ecoleta
